apiVersion: apps/v1
kind: Deployment
metadata:
  name: wa-deployment
  namespace: webapp-challenge
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 501853673872.dkr.ecr.us-east-1.amazonaws.com/api-sample
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m