apiVersion: v1
kind: Service
metadata:
  name: wa-service
  namespace: webapp-challenge
  labels:
    app: wa-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 8095
    targetPort: 8080